### ISSUE TITLE
patient page causes error if the patient was modified

### ISSUE THREAD

**Issue by gjskha** [dvci/health_cards#94] opened 2021-09-16 16:15 UTC
If you create a patient, then go to any given patient page at the `/patients/N` route, where N is the patient ID, it will display fine. Then if you click "Record Immunization" or "Record Lab Result", once it is recorded, when the app redirects back to the `/patients/N` route, you will get an error with a backtrace:

```
ArgumentError (bad argument (expected URI object or URI string)):
lib/health_cards/health_card.rb:202:in `process_reference'
lib/health_cards/health_card.rb:161:in `block (2 levels) in strip_fhir_bundle'
lib/health_cards/health_card.rb:158:in `block in strip_fhir_bundle'
lib/health_cards/health_card.rb:157:in `each'
lib/health_cards/health_card.rb:157:in `strip_fhir_bundle'
lib/health_cards/health_card.rb:128:in `to_hash'
lib/health_cards/health_card.rb:144:in `to_json'
lib/health_cards/health_card.rb:138:in `to_s'
lib/health_cards/issuer.rb:35:in `issue_jws'
app/lib/patient_exporter.rb:36:in `jws'
app/lib/patient_exporter.rb:13:in `qr_codes'
app/controllers/patients_controller.rb:15:in `block (2 levels) in show'
app/controllers/patients_controller.rb:14:in `show'
app/controllers/application_controller.rb:31:in `handle_fhir_errors'
```

However, if you go to the json version e.g. `/patients/N.json` it renders fine. So it appears to be a problem with the HTML rendering.

**Comment by gjskha** [comment] 2021-09-16 16:34
The triggering line looks different from all other format.html calls in that file. Its the first one below.
```
     format.html { @qr_codes = exporter.qr_codes }
        format.html { redirect_to @patient, notice: 'Patient was successfully created.' }
        format.html { render :new, status: :unprocessable_entity }
        format.html { redirect_to @patient, notice: 'Patient was successfully updated.' }
        format.html { render :edit, status: :unprocessable_entity }
      format.html { redirect_to patients_url, notice: 'Patient was successfully destroyed.' }
```

**Comment by ssayer** [comment] 2021-10-01 13:10
Hi @gjskha, I'm having trouble reproducing this locally, but judging from the stack trace the issue seems to be caused by some kind of URL processing issue when creating the health card. This is done when displaying the QR code, which is only done in the HTML version.

It looks like you might be using an old version though, can you update to the latest version of master and let me know if you still have the issue? Also, have you made any modification to the .env files?

**Comment by ssayer** [comment] 2021-10-01 13:17
Also, can you let me know if you're running this on Docker or locally?

**Comment by ssayer** [comment] 2021-10-01 16:17
If you're running on Docker, did you run it as specified in the README?

```
docker build -t health_cards .
docker run -p 3000:3000 --env HOST=http://localhost:3000 health_cards
```

We were able to reproduce this on Docker by leaving out the --env parameter. We'll be adding a default value for this in #97

**Comment by gjskha** [comment] 2021-11-30 17:36
OK. I pulled the latest changes and commented out the specified lines in `handle_fhir_errors`. What I have discovered is that session[:patient_id] value is missing inside of the `health_cards` method of the application_controller file when fetching the `show` controller for Patient, but only with calls subsequent to the patient's creation. This causes @health_card to be empty, which causes the symptom I described. 

I have not made any significant code changes to my sandbox, so I am curious if this can be replicated. If so, then presumably the real fix is to create more robust session management, but maybe there is a quick fix just for the sake of the reference implementation.

**Comment by gjskha** [comment] 2021-11-30 17:39
Not on Docker, FWIW

**Comment by ssayer** [comment] 2021-12-07 15:28
Hey @gjskha, I will see if I can replicate this and report back.

**Comment by ssayer** [comment] 2021-12-07 18:53
@gjskha Can you give me a step by step to reproduce this error? From your description it seems like the patient show page isn't working for new patients, but I can't reproduce any errors.

**Comment by radamson** [comment] 2022-01-25 14:50
@gjskha bumping this issue to see if you are still seeing issues and, if so, can provide step-by-step guidance to help us reproduce it.

**Comment by radamson** [comment] 2022-02-02 15:05
Closing since we're unable to reproduce the issue.

@gjskha feel free to reopen if you're still experiencing issues!

**Closed by radamson** 2022-02-02 15:05 UTC
