### ISSUE TITLE
additional_types aren't inherited

### ISSUE THREAD

**Issue by jmandel** [dvci/health_cards#84] opened 2021-08-13 15:59 UTC
e.g. given https://github.com/dvci/health_cards/blob/4eaa1a5d522fb895a8e15ee188749e1b3129cd02/lib/health_cards/covid_health_card.rb#L11-L12

... the code at https://github.com/HL7/fhir-shc-vaccination-ig/blob/8f1fc04e2f0c81c6b12ea5a2a85189cd5333e849/examples/generate-examples.rb#L6 inadvertently drops the `#covid19` type, so it's missing in https://github.com/HL7/fhir-shc-vaccination-ig/blob/master/examples/Scenario1Bundle-jws-payload-expanded.json#L5-L8

**Comment by jmandel** [comment] 2021-08-13 16:03
Same issue applies for fhir_version.

**Comment by nkarip** [comment] 2021-08-18 17:23
We're tracking this issue now internally in our project Jira, will update here as needed.

**Comment by ssayer** [comment] 2021-09-10 14:42
@nkarip @jmandel The changes to allow inheritance of these attributes are now in master, and should fix this issue. If you can confirm all your issues are addressed, please close this ticket. A few implementation notes below:

- We have set 4.0.1 as the base FHIR version for all health cards. This can be overridden by subclasses, but based on the Zulip topic this seemed to make sense.
- `COVIDImmunizationCard` should now be used instead of `COVIDHealthCard`. We were previously including all types in `COVIDHealthCard`, which I don't think is the expected behavior. Support for actually generating lab cards from the app is still forthcoming.

**Comment by radamson** [comment] 2021-10-01 12:43
I'm going to close this ticket since @ssayer addressed it in https://github.com/dvci/health_cards/pull/87, but if anyone is still seeing issues related to this feel free to reopen it!

**Closed by radamson** 2021-10-01 12:43 UTC
